# Form implementation generated from reading ui file 'lanesDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_LanesDialog(object):
    def setupUi(self, LanesDialog):
        LanesDialog.setObjectName("LanesDialog")
        LanesDialog.resize(528, 400)
        LanesDialog.setMinimumSize(QtCore.QSize(528, 400))
        LanesDialog.setMaximumSize(QtCore.QSize(528, 400))
        LanesDialog.setStyleSheet("QDialog{\n"
"    background-color: #d5d5d5;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    background-color: black;\n"
"    color: white;\n"
"    height: 35px;\n"
"    padding-left: 15px;\n"
"    font-weight: bold;\n"
"    selection-background-color: #2980B9;\n"
"}")
        self.line = QtWidgets.QFrame(parent=LanesDialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 541, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=LanesDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=LanesDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 180, 151, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.direction_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.direction_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.direction_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        self.direction_comboBox.setObjectName("direction_comboBox")
        self.direction_comboBox.addItem("")
        self.direction_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.direction_comboBox)
        self.layoutWidget1 = QtWidgets.QWidget(parent=LanesDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 90, 501, 65))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lane_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lane_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.lane_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lane_lineEdit.setObjectName("lane_lineEdit")
        self.verticalLayout.addWidget(self.lane_lineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(parent=LanesDialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 200, 211, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_lane_btn = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.save_lane_btn.setObjectName("save_lane_btn")
        self.horizontalLayout.addWidget(self.save_lane_btn)
        self.cancel_lane_btn = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.cancel_lane_btn.setObjectName("cancel_lane_btn")
        self.horizontalLayout.addWidget(self.cancel_lane_btn)

        self.retranslateUi(LanesDialog)
        QtCore.QMetaObject.connectSlotsByName(LanesDialog)

    def retranslateUi(self, LanesDialog):
        _translate = QtCore.QCoreApplication.translate
        LanesDialog.setWindowTitle(_translate("LanesDialog", "Dialog"))
        self.label.setText(_translate("LanesDialog", "Add New Lane"))
        self.label_3.setText(_translate("LanesDialog", "Direction"))
        self.direction_comboBox.setItemText(0, _translate("LanesDialog", "Onwards"))
        self.direction_comboBox.setItemText(1, _translate("LanesDialog", "Towards"))
        self.label_2.setText(_translate("LanesDialog", "Lane Width (m)"))
        self.save_lane_btn.setText(_translate("LanesDialog", "Add Lane"))
        self.save_lane_btn.setShortcut(_translate("LanesDialog", "Return"))
        self.cancel_lane_btn.setText(_translate("LanesDialog", "Cancel"))
        self.cancel_lane_btn.setShortcut(_translate("LanesDialog", "Esc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LanesDialog = QtWidgets.QDialog()
    ui = Ui_LanesDialog()
    ui.setupUi(LanesDialog)
    LanesDialog.show()
    sys.exit(app.exec())
