# Form implementation generated from reading ui file 'SectionsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_SectionsDialog(object):
    def setupUi(self, SectionsDialog):
        SectionsDialog.setObjectName("SectionsDialog")
        SectionsDialog.resize(500, 400)
        SectionsDialog.setMinimumSize(QtCore.QSize(500, 400))
        SectionsDialog.setMaximumSize(QtCore.QSize(500, 400))
        self.direction_comboBox = QtWidgets.QComboBox(parent=SectionsDialog)
        self.direction_comboBox.setGeometry(QtCore.QRect(40, 58, 122, 35))
        self.direction_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.direction_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        self.direction_comboBox.setObjectName("direction_comboBox")
        self.direction_comboBox.addItem("")
        self.direction_comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(parent=SectionsDialog)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 122, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lane_lineEdit_4 = QtWidgets.QLineEdit(parent=SectionsDialog)
        self.lane_lineEdit_4.setGeometry(QtCore.QRect(181, 148, 123, 35))
        self.lane_lineEdit_4.setMinimumSize(QtCore.QSize(0, 35))
        self.lane_lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lane_lineEdit_4.setObjectName("lane_lineEdit_4")
        self.lane_lineEdit_5 = QtWidgets.QLineEdit(parent=SectionsDialog)
        self.lane_lineEdit_5.setGeometry(QtCore.QRect(50, 148, 123, 35))
        self.lane_lineEdit_5.setMinimumSize(QtCore.QSize(0, 35))
        self.lane_lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lane_lineEdit_5.setObjectName("lane_lineEdit_5")
        self.label_5 = QtWidgets.QLabel(parent=SectionsDialog)
        self.label_5.setGeometry(QtCore.QRect(181, 120, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=SectionsDialog)
        self.label_7.setGeometry(QtCore.QRect(50, 120, 100, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.edit_lane_btn = QtWidgets.QPushButton(parent=SectionsDialog)
        self.edit_lane_btn.setGeometry(QtCore.QRect(209, 220, 75, 24))
        self.edit_lane_btn.setObjectName("edit_lane_btn")
        self.cancel_lane_btn = QtWidgets.QPushButton(parent=SectionsDialog)
        self.cancel_lane_btn.setGeometry(QtCore.QRect(290, 220, 75, 24))
        self.cancel_lane_btn.setObjectName("cancel_lane_btn")

        self.retranslateUi(SectionsDialog)
        QtCore.QMetaObject.connectSlotsByName(SectionsDialog)

    def retranslateUi(self, SectionsDialog):
        _translate = QtCore.QCoreApplication.translate
        SectionsDialog.setWindowTitle(_translate("SectionsDialog", "Dialog"))
        self.direction_comboBox.setItemText(0, _translate("SectionsDialog", "Straight"))
        self.direction_comboBox.setItemText(1, _translate("SectionsDialog", "Bend"))
        self.label_6.setText(_translate("SectionsDialog", "Section Type"))
        self.label_5.setText(_translate("SectionsDialog", "Radius (m)"))
        self.label_7.setText(_translate("SectionsDialog", "Lenght (m)"))
        self.edit_lane_btn.setText(_translate("SectionsDialog", "Add Lane"))
        self.cancel_lane_btn.setText(_translate("SectionsDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SectionsDialog = QtWidgets.QDialog()
    ui = Ui_SectionsDialog()
    ui.setupUi(SectionsDialog)
    SectionsDialog.show()
    sys.exit(app.exec())
